# Generated by Django 5.2.7 on 2025-10-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_user_id_remove_useraddress_address_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refferdby',
        ),
        migrations.AddField(
            model_name='user',
            name='referredby',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
