# Generated by Django 5.2.7 on 2025-10-30 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_refferdby_user_referredby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referredby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
