# Generated by Django 5.2.7 on 2025-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_referredby_delete_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to='profile_images/'),
        ),
    ]
