# Generated by Django 5.2.7 on 2025-12-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraddress_unique_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
