# Generated by Django 5.2.7 on 2025-12-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_useraddress_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
