# Generated by Django 5.2.7 on 2025-12-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useraddress_name_useraddress_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dcaevmkgg/image/upload/v1764829909/gejrgsa4pnhygnhq32hi.webp', null=True, upload_to='profile_images/'),
        ),
    ]
