# Generated by Django 5.2.7 on 2025-12-04 08:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='gejrgsa4pnhygnhq32hi', max_length=255, null=True, verbose_name='image'),
        ),
    ]
