# Generated by Django 5.2.7 on 2025-12-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraddress',
            name='unique_default_address',
        ),
    ]
