# Generated by Django 5.2.7 on 2025-12-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_useraddress_unique_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work')], default='home', max_length=20),
        ),
    ]
