# Generated by Django 5.2.7 on 2025-12-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referralcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
