# Generated by Django 5.2.7 on 2025-12-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_referralcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='Not provided', max_length=15),
        ),
    ]
