# Generated by Django 5.2.7 on 2025-11-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default='default_value', max_length=500),
            preserve_default=False,
        ),
    ]
