# Generated by Django 5.2.7 on 2025-12-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_coupon_usage_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_type',
            field=models.CharField(default='percentage', max_length=20),
        ),
    ]
