# Generated by Django 5.2.7 on 2025-12-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_categoryoffer_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=set(),
        ),
    ]
