# Generated by Django 5.2.7 on 2025-12-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_couponusage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='name',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
