# Generated by Django 5.2.7 on 2025-12-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productoffer_max_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
