# Generated by Django 5.2.7 on 2025-12-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productoffer_max_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='name',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
