# Generated by Django 5.2.7 on 2025-12-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_productoffer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
    ]
