# Generated by Django 5.2.7 on 2026-01-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productvariant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', '-id']},
        ),
    ]
