# Generated by Django 5.2.7 on 2026-01-07 09:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_cld',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
