# Generated by Django 5.2.7 on 2026-01-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_category_image_cld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_cld',
        ),
    ]
