# Generated by Django 5.2.7 on 2026-01-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='name',
            field=models.CharField(blank=True, default='C-offer', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='name',
            field=models.CharField(blank=True, default='P-offer', max_length=200, null=True),
        ),
    ]
