# Generated by Django 5.2.7 on 2026-01-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_categoryoffer_name_alter_productoffer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryoffer',
            old_name='discount_value',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='productoffer',
            old_name='discount_value',
            new_name='discount_percent',
        ),
    ]
