# Generated by Django 5.2.7 on 2025-11-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_productimage_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
    ]
