# Generated by Django 5.2.7 on 2025-12-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
