# Generated by Django 5.2.7 on 2026-01-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
