# Generated by Django 5.2.7 on 2025-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_orderitem_status_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='offer_percent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
