# Generated by Django 5.2.7 on 2025-12-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_orderitem_offer_percent'),
        ('product', '0005_categoryoffer_created_at_productoffer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.coupon'),
        ),
        migrations.AddField(
            model_name='orders',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
