# Generated by Django 5.2.7 on 2025-12-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_orders_coupon_orders_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_paid',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed')], default='pending'),
        ),
    ]
