# Generated by Django 5.2.7 on 2025-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_orders_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
