# Generated by Django 5.2.7 on 2026-01-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_alter_orders_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallettransaction',
            unique_together=set(),
        ),
    ]
