# Generated by Django 5.2.7 on 2026-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0011_alter_wallettransaction_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('razorpay', 'Credit through Razorpay'), ('item_cancel', 'Refund - Item Cancelled'), ('order_cancel', 'Refund - Order Cancelled'), ('order_return', 'Refund - Order Returned'), ('order_debit', 'Debited for order'), ('referral', 'Referral Bonus')], default='null', max_length=150),
        ),
    ]
