# Generated by Django 5.2.7 on 2026-01-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_wallettransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
