# Generated by Django 5.2.7 on 2026-01-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_orders_refunded_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='original_payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
